### PR TITLE
Added a food card project

### PR DESCRIPTION
**Pull request by saran1522**
added a beautiful food card project built in HTML and CSS. Please review and merge my PR. THANKS!!

### CODE REVIEW

**Comment by mr-robot-2008** [comment]
https://www.github.com/Tanmay-Tiwaricyber


Follow this I'd

**Comment by saran1522** [comment]
followed :)
Please merge it now

**Comment by mr-robot-2008** [comment]
Merged

**Comment by saran1522** [comment]
Thanks :)

**Pull request merged**
